# Generated by Django 4.2.2 on 2023-06-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('rut', models.CharField(error_messages='Debe ingresar rut', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='compraboleto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={},
        ),
    ]
