# Generated by Django 4.2.2 on 2023-06-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_persona_delete_usuario_alter_compraboleto_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='compraBoleto',
        ),
        migrations.DeleteModel(
            name='pelicula',
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
