# Generated by Django 4.2.2 on 2023-06-28 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicacion', '0003_delete_compraboleto_delete_pelicula_delete_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePeli', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('credYreparto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('rut', models.CharField(error_messages='Debe ingresar rut', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='compraBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(choices=[(1, '10:00 AM'), (2, '12:00 PM'), (3, '2:00 PM'), (4, '4:00 PM'), (5, '6:00 PM')], max_length=1)),
                ('cantidad', models.IntegerField()),
                ('f_compra', models.DateField()),
                ('nombrePeli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.pelicula')),
            ],
        ),
    ]
