# Generated by Django 4.2.2 on 2023-06-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(null=True, upload_to='portadas'),
        ),
    ]
