# Generated by Django 4.2.2 on 2023-06-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_pelicula_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='linkTrailer',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
